type User @table {
  username: String!
  email: String
  createdAt: Timestamp!
}

type Task @table {
  title: String!
  description: String
  createdAt: Timestamp!
  dueDate: Timestamp
  isCompleted: Boolean!
  user: User
}